# Generated by Django 3.0.8 on 2020-08-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default-avatar.jpg', null=True, upload_to='users/img'),
        ),
    ]
