# Generated by Django 3.0.8 on 2020-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20200801_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
