# Generated by Django 3.0.8 on 2020-08-11 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_auto_20200807_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='users_answers',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.Test'),
        ),
    ]
