# Generated by Django 3.0.8 on 2020-08-11 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0005_auto_20200811_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='users_answers',
            field=models.ManyToManyField(related_name='users_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
