# Generated by Django 3.0.8 on 2020-08-12 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0007_auto_20200811_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='users_tests', through='tests.UserTests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
