# Generated by Django 3.0.8 on 2020-08-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20200812_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
