# Generated by Django 3.0.8 on 2020-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_testcase_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
