# Generated by Django 3.0.8 on 2020-08-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20200816_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
